"""
Evaluate several destinations and several departure times, and report what
each one measured. Nothing here chooses.

    from src.api.mission_decision import evaluate_mission, DEMONSTRATION_SITES
    matrix = evaluate_mission(sites=DEMONSTRATION_SITES,
                              departure_times=[...])
    matrix.summary()          # which sites and departures routed, and at what
    matrix.select(objective="travel_time_s", direction="min")   # CALLER's rule

WHAT THIS LAYER IS
  A fan-out over the EXISTING orchestration. One scenario is one (site,
  departure time) pair; each is handed to route_profiles.compare_profiles()
  with identical vessel parameters, routing configuration and environmental
  policy, and its answer is recorded verbatim. There is no second A*, no second
  cost model, no second fuel model and no new constraint.

WHAT THIS LAYER REFUSES TO DO
  It does not rank sites, rank departure times, name a best or recommended
  option, or compute an overall score. Those are preferences, and this project
  has none to express. select() exists, but it will not run without a caller
  naming the metric and the direction, and what it returns records that the
  criterion came from the caller.

FEASIBILITY IS THE ROUTER'S WORD, NEVER THIS LAYER'S
  An option is feasible when the existing routing layer returned a route for at
  least one requested profile. It is infeasible only when the router itself
  refused, and the refusal carries the router's OWN outcome and reason. A high
  cost, a high POLARIS penalty, a high iceberg exposure and a high estimated
  fuel are MEASURED ATTRIBUTES, not refusals: nothing here turns a number into
  an infeasibility, and REFUSAL_OUTCOMES is checked against the routing
  module's own vocabulary at import so a new category cannot be invented here.

DEPARTURE TIME IS TWO THINGS AT ONCE
  `departure_time` is the wall clock, which the routing layer checks against
  the environment dates. `departure_offset_s` is how far into the provider's
  own timeline the route starts, which decides the arrival buckets. This module
  derives the second from the first against a stated reference so the two can
  never disagree, and records both.

  A later departure has LESS provider horizon left, not more. On the shipped
  12 h provider a departure at or after 12 h has no bucket left to price at
  all, and the router says so. That is a real limit of the shipped
  configuration, reported as the router words it, not smoothed over.

NOTHING HERE IS AN OPERATIONAL MISSION
  The repository documents one endpoint pair (src/api/config.py DEMO) and no
  station or port coordinates at all. Every other site in DEMONSTRATION_SITES
  is SYNTHETIC, generated by a stated deterministic rule, and carries
  is_operational_mission = False. No synthetic coordinate is described as a
  station, port, base or waypoint.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np

from src.api.config import BEDMACHINE, COMP_CONFIG, DEMO, USNIC
from src.api.environment_provider import (EnvironmentProviderError,
                                          forecast_aware_fields,
                                          resolve_bucket_sources)
from src.api.environment_timeline import (ON_MISSING_PERSIST,
                                          POLICY_LONG_HORIZON_EVALUATION,
                                          POLICY_PERSISTENCE,
                                          plan_environment_timeline,
                                          timeline_summary)
from src.api.environment_forecast import SOURCE_FORECAST, resolver_for_policy
#  The long-horizon harness already defines the evaluation's SCOPE -- which
#  terms are priced, why the iceberg term is omitted, and the validated
#  synthetic geometry. It is imported rather than restated so the two can never
#  drift apart, and so this layer cannot quietly widen the scope.
from src.api.long_horizon_evaluation import (ICEBERG_OMISSION_REASON,
                                             ICEBERG_OMITTED,
                                             _artifact_lineage)
from src.api.environment_forecast import OUT_DIR as FORECAST_DIR
from src.api.long_horizon_evaluation import SCENARIO as LONG_HORIZON_SCENARIO
from src.api.world import environment_dates, fresh_grid, get_world, sic_for_bucket
from src.routing.navigation_cost import load_composition_config
from src.routing.time_navigation_cost import TimeIndexedNavigationCost
from src.routing.end_to_end_route import (OUTCOME_DATE_MISMATCH,
                                          OUTCOME_FORECAST_UNAVAILABLE,
                                          OUTCOME_HARD_CONSTRAINT,
                                          OUTCOME_NO_PATH, OUTCOME_SEARCH_LIMIT)
from src.routing.navigation_domain import NavigationDomain
from src.routing.route_profiles import (ALL_PROFILES, PROFILE_FASTEST,
                                        PROFILE_FUEL, PROFILE_RISK,
                                        PROFILE_SHORTEST, ProfileError,
                                        compare_profiles)

HOUR = 3600.0

#  The refusal vocabulary is the ROUTING module's, imported rather than retyped,
#  so this layer cannot invent a category or drift from it.
REFUSAL_OUTCOMES = (OUTCOME_NO_PATH, OUTCOME_HARD_CONSTRAINT,
                    OUTCOME_FORECAST_UNAVAILABLE, OUTCOME_DATE_MISMATCH,
                    OUTCOME_SEARCH_LIMIT)

#  this layer's own word, for a MATRIX in which nothing routed
NO_FEASIBLE_OPTION = "no_feasible_option"

#  attributes that are measured and reported, and that NEVER make an option
#  infeasible on their own
NOT_FEASIBILITY_CRITERIA = ("configured_cost", "polaris_contribution",
                            "iceberg_exposure_contribution",
                            "max_iceberg_exposure", "estimated_fuel")


class MissionError(ValueError):
    """The mission evaluation cannot be run as specified."""


#  ---------------------------------------------------------------------------
#  POLICIES THIS LAYER WILL ROUTE UNDER
#
#  Exactly two, and the default is the one the demo already used. The forecast
#  policy is reached ONLY when a caller names it: there is no upgrade path from
#  persistence to forecast, silent or otherwise.
#  ---------------------------------------------------------------------------
DEFAULT_POLICY = POLICY_PERSISTENCE
SUPPORTED_POLICIES = (POLICY_PERSISTENCE, POLICY_LONG_HORIZON_EVALUATION)
FORECAST_POLICIES = (POLICY_LONG_HORIZON_EVALUATION,)

MODE_OPERATIONAL_DEMO = "operational_demo"
#  What a long-horizon evaluation mission is NOT. Stated at matrix level so a
#  caller reading only the summary still sees it.
EVALUATION_LIMITATIONS = (
    "iceberg exposure is OMITTED entirely beyond its configured 12 h horizon; "
    "this is not an operational assessment",
    "the sea-ice forecast leads available are 24 h and 48 h only; 6 h and 12 h "
    "have no training target anywhere in the archive",
    "buckets past the last supported lead fall back to the named persistence "
    "rule, which is recorded per bucket rather than presented as a forecast",
    "the 48 h model is an experimental input and is not a proven accuracy "
    "improvement over persistence",
    "currents are not forecast; the provider refuses a non-zero current weight "
    "on any forecast bucket",
)
MODE_LONG_HORIZON_EVALUATION = "long_horizon_scientific_evaluation"

#  the evaluation geometry that has already been validated, offered as a site
#  rather than re-invented. It is SYNTHETIC and says so.
LONG_HORIZON_SITE = None            # bound below, after Site is defined


# ------------------------------------------------------------------ sites
@dataclass(frozen=True)
class Site:
    """One candidate destination cell, and where the coordinate came from."""

    site_id: str
    cell: tuple[int, int]
    label: str
    is_operational: bool
    source: str

    def to_dict(self) -> dict:
        return {"site_id": self.site_id, "cell": list(self.cell),
                "label": self.label, "is_operational": self.is_operational,
                "source": self.source}


#  The rule for every synthetic site below, stated once: take the documented
#  DEMO goal and step a whole number of cells along one grid axis. It is
#  arithmetic on the project's own grid, reproducible from this line alone, and
#  deliberately NOT dressed up as a place.
_SYNTHETIC_RULE = ("the documented DEMO goal offset by a whole number of "
                   "routing-grid cells along one axis; arithmetic on the "
                   "project grid, not a station, port, base or waypoint")

DEMONSTRATION_SITES: tuple[Site, ...] = (
    Site("demo_goal", tuple(DEMO["goal"]), "the documented demonstration goal",
         False, "src/api/config.py DEMO['goal']"),
    Site("site_b", (DEMO["goal"][0], DEMO["goal"][1] - 14),
         "SYNTHETIC demonstration site B", False, _SYNTHETIC_RULE),
    Site("site_c", (DEMO["goal"][0] - 10, DEMO["goal"][1] + 10),
         "SYNTHETIC demonstration site C", False, _SYNTHETIC_RULE),
)

#  The already-validated long-horizon geometry, unchanged: the documented DEMO
#  start to the cell the harness selected deterministically. Synthetic, and
#  never described as a station, port, base or waypoint.
LONG_HORIZON_SITE = Site(
    "long_horizon_demo",
    tuple(LONG_HORIZON_SCENARIO["goal"]),
    "SYNTHETIC long-horizon demonstration destination",
    False,
    "src/api/long_horizon_evaluation.py SCENARIO['goal'] -- "
    + LONG_HORIZON_SCENARIO["goal_selection_rule"])
LONG_HORIZON_START = tuple(LONG_HORIZON_SCENARIO["start"])


# --------------------------------------------------------------- scenario
@dataclass(frozen=True)
class MissionScenario:
    """One (site, departure time) alternative, fully specified."""

    scenario_id: str
    start: tuple[int, int]
    site: Site
    departure_time: datetime
    departure_offset_s: float
    vessel_speed_mps: float
    polaris_ice_class: str
    polaris_riv_table: str
    profiles: tuple[str, ...]
    environment_policy: str
    is_operational_mission: bool
    #  PHASE 3 / 9: an evaluation run is not an operational assessment, and
    #  says so on the scenario itself rather than only deep inside a route
    evaluation_mode: str = MODE_OPERATIONAL_DEMO
    is_operational_assessment: bool = True
    iceberg_exposure: str = "priced"
    iceberg_omission_reason: str | None = None
    horizon_buckets: int | None = None
    forecast_dir: str | None = None

    def to_dict(self) -> dict:
        return {
            "scenario_id": self.scenario_id,
            "start": list(self.start),
            "destination": self.site.to_dict(),
            "departure_time": self.departure_time.isoformat(),
            "departure_offset_s": float(self.departure_offset_s),
            "vessel_speed_mps": float(self.vessel_speed_mps),
            "polaris_ice_class": self.polaris_ice_class,
            "polaris_riv_table": self.polaris_riv_table,
            "profiles_requested": list(self.profiles),
            "environment_policy": self.environment_policy,
            "is_operational_mission": self.is_operational_mission,
            "evaluation_mode": self.evaluation_mode,
            "is_operational_assessment": self.is_operational_assessment,
            "iceberg_exposure": self.iceberg_exposure,
            "iceberg_omission_reason": self.iceberg_omission_reason,
            "horizon_buckets": self.horizon_buckets,
            "forecast_dir": self.forecast_dir,
        }


# ----------------------------------------------------------------- result
@dataclass(frozen=True)
class MissionOption:
    """What one scenario measured, or why the router refused it."""

    scenario: MissionScenario
    feasible: bool
    refusal_outcome: str | None
    refusal_reason: str | None
    profiles: dict = field(default_factory=dict)
    environment: dict = field(default_factory=dict)

    def objective_values(self) -> dict:
        """Per profile, the attributes Phase 6 asks for. Measured, not judged."""
        out = {}
        for name, p in self.profiles.items():
            if not p.get("success"):
                out[name] = {"routed": False, "outcome": p.get("outcome"),
                             "reason": p.get("reason")}
                continue
            row = {
                "routed": True,
                "distance_km": p.get("distance_km"),
                "travel_time_h": p.get("travel_time_h"),
                "configured_cost": p.get("configured_cost"),
                "polaris_contribution": p.get("polaris_contribution"),
                "environmental_contribution": p.get("environmental_contribution"),
                "iceberg_exposure_contribution":
                    p.get("iceberg_exposure_contribution"),
                "max_iceberg_exposure": p.get("max_iceberg_exposure"),
                "estimated_fuel": p.get("estimated_fuel"),
                "estimated_fuel_units": p.get("estimated_fuel_units"),
                "estimated_fuel_per_km": p.get("estimated_fuel_per_km"),
                "cells": len(p.get("path") or ()),
            }
            if name == PROFILE_SHORTEST:
                row["is_a_fuel_figure"] = False
            out[name] = row
        return out

    def provenance(self) -> dict:
        """PHASE 8: everything needed to say what this option actually was."""
        d = self.scenario.to_dict()
        d.update({
            "feasible": self.feasible,
            "refusal_outcome": self.refusal_outcome,
            "refusal_reason": self.refusal_reason,
            "environment": self.environment,
            "estimated_fuel_provenance": self._fuel_provenance(),
            "iceberg_exposure": self._iceberg_status(),
            "feasibility_is_the_routers_word": True,
            "attributes_that_never_cause_a_refusal":
                list(NOT_FEASIBILITY_CRITERIA),
        })
        return d

    def _fuel_provenance(self) -> dict | None:
        for p in self.profiles.values():
            if p.get("success") and p.get("fuel_provenance"):
                return p["fuel_provenance"]
        return None

    def _iceberg_status(self) -> dict:
        if self.scenario.iceberg_exposure == ICEBERG_OMITTED:
            return {"status": ICEBERG_OMITTED,
                    "reason": self.scenario.iceberg_omission_reason,
                    "reinterpreted_24h_or_48h_rasters": False,
                    "zero_filled": False, "persisted": False,
                    "is_an_operational_assessment": False}
        for p in self.profiles.values():
            if p.get("success") and p.get("iceberg_provenance"):
                return dict(p["iceberg_provenance"], status="priced")
        return {"status": "not_priced",
                "reason": "no profile routed, so nothing was priced"}

    def to_dict(self) -> dict:
        return {"scenario": self.scenario.to_dict(),
                "feasible": self.feasible,
                "refusal_outcome": self.refusal_outcome,
                "refusal_reason": self.refusal_reason,
                "objectives": self.objective_values(),
                "provenance": self.provenance()}


# ----------------------------------------------------------------- matrix
@dataclass(frozen=True)
class MissionMatrix:
    """Every alternative that was evaluated. Not a ranking."""

    options: tuple[MissionOption, ...]
    start: tuple[int, int]
    sites: tuple[Site, ...]
    departure_times: tuple[datetime, ...]
    profiles: tuple[str, ...]
    environment_policy: str
    evaluation_mode: str = MODE_OPERATIONAL_DEMO
    is_operational_assessment: bool = True
    iceberg_exposure: str = "priced"
    limitations: tuple[str, ...] = ()

    @property
    def feasible(self) -> tuple[MissionOption, ...]:
        return tuple(o for o in self.options if o.feasible)

    @property
    def any_feasible(self) -> bool:
        return bool(self.feasible)

    def summary(self) -> dict:
        """PHASE 7: the questions a caller may ask, and no verdict."""
        feas = self.feasible
        by_site, by_departure = {}, {}
        for o in self.options:
            by_site.setdefault(o.scenario.site.site_id, []).append(o.feasible)
            by_departure.setdefault(
                o.scenario.departure_time.isoformat(), []).append(o.feasible)
        objectives_available = sorted({
            name for o in feas for name, v in o.objective_values().items()
            if v.get("routed")})
        out = {
            "start": list(self.start),
            "environment_policy": self.environment_policy,
            "evaluation_mode": self.evaluation_mode,
            "is_operational_assessment": self.is_operational_assessment,
            "iceberg_exposure": self.iceberg_exposure,
            "limitations": list(self.limitations),
            "profiles_requested": list(self.profiles),
            "options_evaluated": len(self.options),
            "options_feasible": len(feas),
            "sites_feasible": sorted(k for k, v in by_site.items() if any(v)),
            "sites_infeasible": sorted(k for k, v in by_site.items()
                                       if not any(v)),
            "departures_feasible": sorted(k for k, v in by_departure.items()
                                          if any(v)),
            "departures_infeasible": sorted(k for k, v in by_departure.items()
                                            if not any(v)),
            "objectives_available": objectives_available,
            "options": [
                {"scenario_id": o.scenario.scenario_id,
                 "site": o.scenario.site.site_id,
                 "departure_time": o.scenario.departure_time.isoformat(),
                 "feasible": o.feasible,
                 "refusal_outcome": o.refusal_outcome,
                 "refusal_reason": o.refusal_reason,
                 "environment_source_types":
                     o.environment.get("source_types"),
                 "environment_models": o.environment.get("models"),
                 "buckets_used": o.environment.get("buckets_used"),
                 "objectives": o.objective_values()}
                for o in self.options],
            "route_differences": self._differences(),
            #  the things this layer will not say
            "this_is_not_a_ranking": True,
            "has_a_best_site": False,
            "has_a_best_departure_time": False,
            "has_a_recommended_route": False,
            "has_an_overall_score": False,
            "selection_requires_a_caller_supplied_objective": True,
        }
        if not feas:
            out["outcome"] = NO_FEASIBLE_OPTION
            out["no_feasible_option"] = True
            out["why"] = sorted({
                f"{o.refusal_outcome}: {o.refusal_reason}"
                for o in self.options if o.refusal_outcome})
        else:
            out["outcome"] = "options_evaluated"
            out["no_feasible_option"] = False
        return out

    def _differences(self) -> list:
        """Where the returned geometry differs, per site, across departures.
        A measurement, with no claim about which one is preferable."""
        rows = []
        for site in self.sites:
            paths = {}
            for o in self.options:
                if o.scenario.site.site_id != site.site_id:
                    continue
                p = o.profiles.get(PROFILE_RISK) or {}
                if o.feasible and p.get("success"):
                    paths[o.scenario.departure_time.isoformat()] = \
                        tuple(tuple(c) for c in p["path"])
            if len(paths) < 2:
                continue
            keys = sorted(paths)
            first = paths[keys[0]]
            for k in keys[1:]:
                other = paths[k]
                shared = len(set(first) & set(other))
                diverge = next((i for i, (a, b) in enumerate(zip(first, other))
                                if a != b), None)
                rows.append({
                    "site": site.site_id, "profile": PROFILE_RISK,
                    "departure_a": keys[0], "departure_b": k,
                    "path_changed": first != other,
                    "shared_cells": shared,
                    "first_divergence_index": diverge})
        return rows

    def select(self, *, objective: str, direction: str,
               among: str = "feasible") -> dict:
        """Pick one option BY A CRITERION THE CALLER SUPPLIED.

        There is no default objective and no default direction, because a
        default would be this layer expressing a preference. The answer records
        whose criterion it was.
        """
        if objective not in NOT_FEASIBILITY_CRITERIA + (
                "distance_km", "travel_time_h", "estimated_fuel_per_km"):
            raise MissionError(
                f"{objective!r} is not a measured attribute of an option; "
                f"choose one of {sorted(set(NOT_FEASIBILITY_CRITERIA) | {'distance_km', 'travel_time_h', 'estimated_fuel_per_km'})}")
        if direction not in ("min", "max"):
            raise MissionError(
                f"direction must be 'min' or 'max', got {direction!r}; this "
                f"layer has no opinion about which way is better")
        if among != "feasible":
            raise MissionError("only feasible options can be selected among")
        rows = []
        for o in self.feasible:
            for name, v in o.objective_values().items():
                if v.get("routed") and v.get(objective) is not None:
                    rows.append((float(v[objective]), o, name))
        if not rows:
            return {"selected": None,
                    "why": f"no feasible option reports {objective}",
                    "criterion_supplied_by": "caller"}
        best = (min if direction == "min" else max)(rows, key=lambda r: r[0])
        value, option, profile = best
        ties = [r for r in rows if r[0] == value]
        return {
            "selected": {"scenario_id": option.scenario.scenario_id,
                         "site": option.scenario.site.site_id,
                         "departure_time":
                             option.scenario.departure_time.isoformat(),
                         "profile": profile, "value": value},
            "objective": objective, "direction": direction,
            "ties": len(ties),
            "criterion_supplied_by": "caller",
            "this_is_not_a_recommendation": True,
            "what_this_means": (
                f"among the feasible options, this one has the {direction}imum "
                f"{objective}. That is arithmetic on the caller's criterion, "
                f"not a judgement by this system that it is the option to "
                f"take."),
        }

    def to_dict(self) -> dict:
        return {"start": list(self.start),
                "sites": [s.to_dict() for s in self.sites],
                "departure_times": [d.isoformat() for d in self.departure_times],
                "profiles_requested": list(self.profiles),
                "environment_policy": self.environment_policy,
                "evaluation_mode": self.evaluation_mode,
                "is_operational_assessment": self.is_operational_assessment,
                "iceberg_exposure": self.iceberg_exposure,
                "limitations": list(self.limitations),
                "options": [o.to_dict() for o in self.options],
                "summary": self.summary()}


# ------------------------------------------------------------- evaluation
def _res(bucket: dict, key: str):
    """Read a field either from the bucket record or from the resolver's own
    answer nested under it. One lookup, two shapes, no filename parsing."""
    if bucket.get(key) is not None:
        return bucket[key]
    return (bucket.get("resolution") or {}).get(key)


def _with_lineage(bucket: dict, *, forecast_dir=None) -> dict:
    """Add the artifact lineage to one forecast-priced bucket.

    The resolution is by SHA match, exactly as the long-horizon harness does
    it: the raster names its model artifact and that artifact's SHA, and the
    training metrics file whose recorded artifact SHA equals it names the
    dataset. Never by filename, lead number or ordering.
    """
    out = dict(bucket)
    if out.get("source_type") != SOURCE_FORECAST:
        return out
    name = (out.get("resolution") or {}).get("path")
    if not name:
        return out
    out.update(_artifact_lineage(Path(forecast_dir or FORECAST_DIR) / name))
    return out


def _environment_for(world, option_profiles: dict, *, timeline=None,
                     field_provenance=None, forecast_dir=None) -> dict:
    """The environmental provenance for the buckets THIS option actually used.

    Under the forecast policy the summary comes from the option's OWN timeline,
    never from the world's persistence summary, and every forecast-priced
    bucket is enriched with the artifact lineage the harness already resolves
    by SHA match.
    """
    summary = (dict(timeline_summary(timeline)) if timeline is not None
               else dict(world["environment_summary"]))
    used = set()
    for p in option_profiles.values():
        if p.get("success"):
            used.update(int(b) for b in (p.get("buckets_used") or ()))
    if field_provenance is not None:
        #  the fields' own records, which carry the resolver's full answer
        buckets = [_with_lineage(dict(field_provenance[b], bucket=b),
                                 forecast_dir=forecast_dir)
                   for b in sorted(used) if b in field_provenance]
    else:
        buckets = [b for b in summary.get("buckets", [])
                   if int(b.get("bucket", -1)) in used]
    return {
        "policy": summary.get("policy"),
        "analysis_date": summary.get("analysis_date"),
        "environment_dates": summary.get("environment_dates"),
        "environment_is_time_varying": summary.get(
            "environment_is_time_varying"),
        "source_types": sorted({b.get("source_type") for b in buckets}) or None,
        "models": sorted({b["model"] for b in buckets if b.get("model")}) or [],
        "forecast_origins": sorted({_res(b, "forecast_origin") for b in buckets
                                    if _res(b, "forecast_origin")}) or [],
        "forecast_leads": sorted({_res(b, "lead_hours") for b in buckets
                                  if _res(b, "lead_hours") is not None}) or [],
        "validity_rules": sorted({_res(b, "validity_rule") for b in buckets
                                  if _res(b, "validity_rule")}) or [],
        "artifacts": sorted({_res(b, "path") for b in buckets
                             if _res(b, "path")}) or [],
        "buckets_used": sorted(used),
        "buckets": buckets,
    }


def _long_horizon_environment(policy: str, *, departure: datetime, buckets: int,
                              world, bucket_hours: float,
                              forecast_dir: Path | None = None):
    """Build the evaluation provider for one departure, from scratch.

    This is the whole integration seam. The evaluation harness and the mission
    layer already converge on route_profiles.compare_profiles(); all that was
    missing was a provider built from the forecast-aware fields instead of the
    world's persistence provider, and the per-bucket sea ice that goes with it.

    Returns (provider, sic_for_bucket, timeline, sources). The provider carries
    NO iceberg layer: see ICEBERG_OMISSION_REASON, which is imported from the
    harness rather than restated here.
    """
    if policy not in SUPPORTED_POLICIES:
        raise MissionError(f"{policy!r} is not a supported policy")
    forecast = policy in FORECAST_POLICIES
    bucket_list = list(range(int(buckets)))
    kw = {} if forecast_dir is None else {"forecast_dir": Path(forecast_dir)}
    common = dict(buckets=bucket_list, bucket_seconds=bucket_hours * HOUR,
                  departure_time=departure, analysis_date=world["day"],
                  available_dates=environment_dates())

    def resolver():
        """None for persistence: the baseline resolves no forecast at all.
        This is the same construction src/api/long_horizon_evaluation.py uses
        for its own two runs, so the baseline here IS that baseline."""
        if not forecast:
            return None
        return resolver_for_policy(policy, origin_time=departure, **kw)

    timeline = (plan_environment_timeline(policy=policy, **common) if not forecast
                else plan_environment_timeline(
                    policy=policy, on_missing=ON_MISSING_PERSIST,
                    resolver=resolver(), **common))
    fields = forecast_aware_fields(
        timeline=timeline,
        resolver=resolver(),
        grid=world["grid"], constraints=world["constraints"],
        polaris_penalties=world["polaris"].penalties,
        comp_config=load_composition_config(COMP_CONFIG), usnic_dir=USNIC,
        chart_date=world["chart_date"], analysis_date=world["day"],
        bucket_hours=bucket_hours, sic_for_date=lambda day: world["grid"])
    #  The per-bucket sea ice the fuel proxy needs. resolve_bucket_sources is
    #  the SAME call forecast_aware_fields makes internally, so the two must
    #  name the same artifact for every bucket -- checked, not assumed.
    sources = resolve_bucket_sources(
        timeline, resolver=resolver(),
        grid=world["grid"], sic_for_date=lambda day: world["grid"])
    by_field = {f.bucket: (f.environment.get("resolution") or {}).get("path")
                for f in fields}
    #  Keep ONE array per distinct source, not one per bucket. Sixteen buckets
    #  over three sources would otherwise hold sixteen full 1328x1264 grids --
    #  about 215 MB of identical data, which is enough to end the process.
    sic_by_key: dict = {}
    bucket_key: dict = {}
    for src in sources:
        want = src.resolution.path.name if src.resolution else None
        if by_field.get(src.bucket) != want:
            raise MissionError(
                f"bucket {src.bucket} was priced from {by_field.get(src.bucket)!r} "
                f"but its sea-ice field was read from {want!r}; the fuel proxy "
                f"and the routing cost must read the same artifact")
        key = (src.origin, want or src.entry.environment_date.isoformat())
        sic_by_key.setdefault(key, src.sic)
        bucket_key[int(src.bucket)] = key
    source_count = len(sic_by_key)
    del sources

    #  NO iceberg layer, deliberately: the configured exposure horizon is 12 h
    provider = TimeIndexedNavigationCost.from_fields(
        fields, bucket_seconds=bucket_hours * HOUR,
        allow_historical_demo_mismatch=True)

    def sic_for(bucket: int):
        try:
            return sic_by_key[bucket_key[int(bucket)]]
        except KeyError:
            raise MissionError(
                f"no sea-ice field was resolved for bucket {bucket}; the fuel "
                f"proxy will not fall back to another bucket's ice") from None

    #  The FIELDS carry the resolver's full answer per bucket (resolution:
    #  path, lead, validity rule and window). The timeline summary does not, so
    #  the per-bucket provenance is taken from the fields -- the same records
    #  the long-horizon harness reports -- never parsed out of a filename.
    field_provenance = {int(f.bucket): dict(f.environment or {}) for f in fields}
    return provider, sic_for, timeline, field_provenance


def evaluate_scenario(scenario: MissionScenario, *, world=None,
                      risk_provider=None, grid_factory=None) -> MissionOption:
    """Route ONE scenario through the existing orchestration, from scratch.

    Nothing is carried over from another scenario: a fresh grid, a fresh
    constraint layer and a fresh comparison every time, with this scenario's
    own departure offset deciding its own arrival buckets.
    """
    world = world or get_world()
    #  A world for another DATE brings its own grid factory: fresh_grid() is
    #  bound to the shipped demo day, so an evaluation over a different day
    #  must supply its own or it would route on the wrong grid.
    grid_factory = grid_factory or fresh_grid
    forecast_timeline = None
    field_provenance = None
    if scenario.evaluation_mode == MODE_LONG_HORIZON_EVALUATION:
        #  the OPT-IN path: a provider built from the forecast-aware fields,
        #  with no iceberg layer. Nothing here can be reached without the
        #  caller having named this policy.
        try:
            provider, sic_source, forecast_timeline, field_provenance = \
                _long_horizon_environment(
                    scenario.environment_policy,
                    departure=scenario.departure_time,
                    buckets=int(scenario.horizon_buckets or 0),
                    world=world, bucket_hours=float(DEMO["bucket_hours"]),
                    forecast_dir=(Path(scenario.forecast_dir)
                                  if scenario.forecast_dir else None))
        except (EnvironmentProviderError, ValueError) as exc:
            if isinstance(exc, MissionError):
                raise
            return MissionOption(
                scenario=scenario, feasible=False,
                refusal_outcome=OUTCOME_FORECAST_UNAVAILABLE,
                refusal_reason=str(exc))
    else:
        provider = risk_provider or world["provider"]
        sic_source = sic_for_bucket()
    try:
        comparison = compare_profiles(
            grid_factory, risk_provider=provider, usnic_dir=USNIC,
            start=tuple(scenario.start), goal=tuple(scenario.site.cell),
            departure_time=scenario.departure_time,
            vessel_speed_mps=scenario.vessel_speed_mps,
            constraints_factory=lambda g: NavigationDomain(g).add_geotiff(
                "land_mask", BEDMACHINE),
            polaris_ice_class=scenario.polaris_ice_class,
            polaris_riv_table=scenario.polaris_riv_table,
            polaris_penalties=world["polaris"],
            sic_for_bucket=sic_source,
            allow_historical_demo_override=True,
            departure_offset_s=float(scenario.departure_offset_s))
    except ProfileError as exc:
        return MissionOption(
            scenario=scenario, feasible=False,
            refusal_outcome=OUTCOME_HARD_CONSTRAINT, refusal_reason=str(exc))

    payload = comparison.to_dict()["profiles"]
    wanted = {n: payload[n] for n in scenario.profiles if n in payload}
    routed = {n: p for n, p in wanted.items() if p.get("success")}
    env = _environment_for(world, routed, timeline=forecast_timeline,
                           field_provenance=field_provenance,
                           forecast_dir=(Path(scenario.forecast_dir)
                                         if scenario.forecast_dir else None))

    if routed:
        return MissionOption(scenario=scenario, feasible=True,
                             refusal_outcome=None, refusal_reason=None,
                             profiles=wanted, environment=env)

    #  every requested profile was refused. The outcome is the ROUTER's, taken
    #  from the profile that was asked for first, and it must be one the
    #  routing module defines -- never a threshold invented here.
    first = wanted[next(iter(wanted))] if wanted else {}
    outcome = first.get("outcome")
    if outcome not in REFUSAL_OUTCOMES:
        raise MissionError(
            f"the routing layer refused with {outcome!r}, which is not one of "
            f"its own refusal outcomes {REFUSAL_OUTCOMES}. This layer will not "
            f"classify an unknown outcome as an infeasibility.")
    return MissionOption(scenario=scenario, feasible=False,
                         refusal_outcome=outcome,
                         refusal_reason=first.get("reason"),
                         profiles=wanted, environment=env)


def evaluate_mission(*, sites, departure_times, start=None,
                     reference_departure: datetime | None = None,
                     vessel_speed_mps: float | None = None,
                     polaris_ice_class: str | None = None,
                     polaris_riv_table: str | None = None,
                     profiles: tuple[str, ...] = ALL_PROFILES,
                     environment_policy: str | None = None,
                     horizon_buckets: int | None = None,
                     grid_factory=None, forecast_dir=None,
                     world=None) -> MissionMatrix:
    """Evaluate every (site, departure time) pair independently.

    environment_policy defaults to persistence -- the demo's policy, unchanged.
    The forecast policy is reached only by naming it.
    """
    world = world or get_world()
    start = tuple(start or DEMO["start"])
    reference = reference_departure or datetime.fromisoformat(
        DEMO["departure_time"])
    speed = float(DEMO["vessel_speed_mps"] if vessel_speed_mps is None
                  else vessel_speed_mps)
    ice_class = polaris_ice_class or DEMO["polaris_ice_class"]
    riv = polaris_riv_table or DEMO["polaris_riv_table"]
    sites = tuple(sites)
    departure_times = tuple(departure_times)
    if not sites:
        raise MissionError("at least one candidate destination is required")
    if not departure_times:
        raise MissionError("at least one departure time is required")
    unknown = [p for p in profiles if p not in ALL_PROFILES]
    if unknown:
        raise MissionError(f"unknown profiles {unknown}; have {ALL_PROFILES}")

    policy = environment_policy or DEFAULT_POLICY
    if policy not in SUPPORTED_POLICIES:
        raise MissionError(
            f"{policy!r} is not a policy this layer routes under; it supports "
            f"{list(SUPPORTED_POLICIES)}. The requested policy is refused "
            f"rather than replaced with a supported one.")
    forecast = policy in FORECAST_POLICIES
    #  EVALUATION MODE is entered by asking for a forecast policy, or by asking
    #  for a horizon longer than the world's own provider. Either way it is the
    #  caller's explicit request: the default path -- no policy, no horizon --
    #  is the shipped demo configuration, untouched.
    evaluation = forecast or horizon_buckets is not None
    if not evaluation:
        #  the default path must still be the policy the world actually
        #  resolved, so persistence cannot silently mean something else
        resolved = world["environment_summary"].get("policy")
        if resolved != policy:
            raise MissionError(
                f"this backend resolved the environment under {resolved!r}, "
                f"but the mission asked for {policy!r}")
    planned = (int(horizon_buckets or LONG_HORIZON_SCENARIO["buckets"])
               if evaluation else None)
    if planned is not None and planned < 1:
        raise MissionError(f"horizon_buckets must be >= 1, got {planned}")
    mode = (MODE_LONG_HORIZON_EVALUATION if evaluation
            else MODE_OPERATIONAL_DEMO)
    options = []
    for site in sites:
        for departure in departure_times:
            offset = (departure - reference).total_seconds()
            if offset < 0:
                raise MissionError(
                    f"departure {departure.isoformat()} is before the "
                    f"reference {reference.isoformat()}; the provider's "
                    f"timeline does not extend backwards")
            scenario = MissionScenario(
                scenario_id=f"{site.site_id}@{departure.isoformat()}",
                start=start, site=site, departure_time=departure,
                departure_offset_s=offset, vessel_speed_mps=speed,
                polaris_ice_class=ice_class, polaris_riv_table=riv,
                profiles=tuple(profiles), environment_policy=policy,
                evaluation_mode=mode,
                #  PHASE 3: an evaluation run omits the iceberg term, so it is
                #  NOT an operational assessment and never claims to be
                is_operational_assessment=not evaluation,
                iceberg_exposure=(ICEBERG_OMITTED if evaluation else "priced"),
                iceberg_omission_reason=(ICEBERG_OMISSION_REASON if evaluation
                                         else None),
                horizon_buckets=planned,
                forecast_dir=(str(forecast_dir) if forecast_dir else None),
                #  DERIVED, never asserted: a mission is operational only if
                #  its destination is a real operational location, and no
                #  coordinate in this repository is one. Computing it here
                #  means a synthetic site can never be labelled operational by
                #  someone editing a default.
                is_operational_mission=bool(site.is_operational))
            options.append(evaluate_scenario(
                scenario, world=world, grid_factory=grid_factory,
                risk_provider=world.get("provider")))
    return MissionMatrix(
        options=tuple(options), start=start, sites=sites,
        departure_times=departure_times, profiles=tuple(profiles),
        environment_policy=policy, evaluation_mode=mode,
        is_operational_assessment=not evaluation,
        iceberg_exposure=(ICEBERG_OMITTED if evaluation else "priced"),
        limitations=(EVALUATION_LIMITATIONS if evaluation else ()))


def main() -> int:
    """The demonstration matrix: three sites x four departure times."""
    import json
    base = datetime.fromisoformat(DEMO["departure_time"])
    departures = [base + timedelta(hours=h) for h in (0, 6, 12, 18)]
    m = evaluate_mission(sites=DEMONSTRATION_SITES, departure_times=departures)
    s = m.summary()
    print("=" * 78)
    print("MISSION DECISION MATRIX -- no site, departure or route is ranked")
    print("=" * 78)
    print(f"  start {m.start}  policy {m.environment_policy}")
    print(f"  {s['options_feasible']} of {s['options_evaluated']} options "
          f"routed; outcome {s['outcome']}")
    print()
    for o in m.options:
        sc = o.scenario
        head = f"  {sc.site.site_id:<11} {sc.departure_time.strftime('%d %H:%M')}"
        if not o.feasible:
            print(f"{head}  INFEASIBLE  {o.refusal_outcome}")
            print(f"{'':<26}{(o.refusal_reason or '')[:78]}")
            continue
        print(f"{head}  feasible")
        for name, v in o.objective_values().items():
            if not v["routed"]:
                print(f"{'':<26}{name:<18} refused: {v['outcome']}")
                continue
            print(f"{'':<26}{name:<18} {v['distance_km']:8.3f} km "
                  f"{v['travel_time_h']:7.3f} h  cost {v['configured_cost']:,.1f}"
                  f"  fuel {v['estimated_fuel']:,.0f} OWE-m")
    print()
    print(json.dumps({k: v for k, v in s.items()
                      if k not in ("options", "route_differences")}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
